## 파이썬 3

In [8]:
score = int(input("점수: "))
message = "success" if score >= 60 else "failure"
print(message)

success


In [11]:
numbers = [1,2,3,4]
squares = [x**2  for x in numbers]
print(squares)

[1, 4, 9, 16]


In [13]:
numbers = [1,2,3,4]
squares = []
for x in numbers:
    squares.append(x**2)
print(squares)

[1, 4, 9, 16]


In [18]:
numbers = [1,2,3,4,5,6,7]
even_numbers = [  x**2  for x in numbers if x%2 == 0]
print(even_numbers)

[4, 16, 36]


## 넘파이

In [22]:
import numpy as np

In [23]:
np.__version__

'2.2.1'

In [24]:
a = [1,2,3,4]
a 

[1, 2, 3, 4]

In [25]:
type(a)

list

In [26]:
int_arr = np.array([1,2,3,4])
int_arr


array([1, 2, 3, 4])

In [27]:
print(int_arr)

[1 2 3 4]


In [28]:
print(type(int_arr))

<class 'numpy.ndarray'>


In [32]:
list_data = [1,2.2,3,'3.3']

arr = np.array(list_data)

print(arr)
print(type(arr))

['1' '2.2' '3' '3.3']
<class 'numpy.ndarray'>


In [35]:
arr1 = np.arange(1,10,2)

arr1

array([1, 3, 5, 7, 9])

In [41]:
arr1  = np.zeros((2,5))
print(arr1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [52]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],
                [[9,10,11,12],[13,14,15,16]],
                [[9,10,11,12],[5,6,7,8]]])

print(arr)
print(arr.ndim)
print(arr.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[ 9 10 11 12]
  [ 5  6  7  8]]]
3
(3, 2, 4)


In [66]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [67]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(type(a),type(b))

a*b

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


array([ 4, 10, 18])

In [68]:
data = [0,1,2,3,4,5,6,7,8,9]
data_do = []
for i in data:
    data_do.append(i*2)
print(data_do)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [70]:
data1 = np.array([1,2,3,4,5,6,7])
data1*2


array([ 2,  4,  6,  8, 10, 12, 14])

In [72]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],
                [[9,10,11,12],[13,14,15,16]],
                [[9,10,11,12],[5,6,7,8]]])

print(arr.size)

24


In [76]:
a = np.array([[0, 1, 2],[3,4,5]])
print(a[0,0])
print(a[0,1])
print(a[1,2])

0
1
5


In [82]:
a = np.array([[0, 1, 2,3],[4,5,6,7]])
print(a[:2,:2])

[[0 1]
 [4 5]]


In [86]:
a = np.array([1,2,3])
b = np.array([10,20,30])
print(2 * a+b)
print(a == 2)
print(b >10)
print((a==2)&(b>10))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


In [88]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True,False,True,False,False,True,False,True,True,False])
a[idx]

array([0, 2, 5, 7, 8])

In [90]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
a%2 == 0
a[a%2 == 0]

array([0, 2, 4, 6, 8])

In [91]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([0,2,4,6,7])
a[idx]

array([0, 2, 4, 6, 7])

In [93]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a[:,[0,3]]
             

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [98]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a[[2,0,1],:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [203]:
x = np.arange(1,21) 
x.reshape(2,-1)
print(x)
print(x[x%3==0])
print(x[x%4==1])
print(x[(x %3 ==0) & (x %4 ==1)])


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


## 판다스

Note: you may need to restart the kernel to use updated packages.


In [140]:
import pandas as pd

In [130]:
s = pd.Series([3,-5,7,4],index=['a','b','c','d'])

In [131]:
s * 3

a     9
b   -15
c    21
d    12
dtype: int64

In [134]:
df = pd.DataFrame({'Division':['부산광역시','전라남도','강원도'],'Code':['051','061','033'],'Population':[2165156,456456,456484]})
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


Division Code  Population
0    부산광역시  051     2165156
1     전라남도  061      456456
2      강원도  033      456484

In [135]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [136]:
df.columns

Index(['Division', 'Code', 'Population'], dtype='object')

In [137]:
df.values

array([['부산광역시', '051', 2165156],
       ['전라남도', '061', 456456],
       ['강원도', '033', 456484]], dtype=object)

In [138]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Division    3 non-null      object
 1   Code        3 non-null      object
 2   Population  3 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes


In [139]:
df.set_index('Division')

Code  Population
Division                 
부산광역시     051     2165156
전라남도      061      456456
강원도       033      456484

In [142]:
df = pd.read_csv('heroes.csv')
df

이름  나이     직업     국적    키            재산
0   아이언맨  58    CEO     미국  174  1.150000e+10
1     토르  45      신  아스가르드  190           NaN
2  스파이더맨  18   고등학생     미국  177  6.000000e+02
3   원더우먼  27     공주  데미스키라  178           NaN
4     헐크  33  핵물리학자     미국  270  1.000000e+09
5   캡틴마블  25    파일럿     미국  170  3.400000e+08
6  블랙위도우  32    스파이    러시아  170  5.000000e+07

In [144]:
pd.options.display.float_format = '{:.0f}'.format
df

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [145]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [148]:
df.head()

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000

In [149]:
df.tail()

이름  나이     직업     국적    키         재산
2  스파이더맨  18   고등학생     미국  177        600
3   원더우먼  27     공주  데미스키라  178        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
5   캡틴마블  25    파일럿     미국  170  340000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [150]:
df.describe()

나이   키          재산
count   7   7           5
mean   34 190  2578000120
std    13  36  5003440739
min    18 170         600
25%    26 172    50000000
50%    32 177   340000000
75%    39 184  1000000000
max    58 270 11500000000

In [154]:
df['국적'].unique()

array(['미국', '아스가르드', '데미스키라', '러시아'], dtype=object)

In [ ]:
df['국적'].unique()

In [155]:
df['국적'].value_counts()

국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64

In [158]:
df['나이'].nlargest(7)

0    58
1    45
4    33
6    32
3    27
5    25
2    18
Name: 나이, dtype: int64

In [ ]:
df.nlargest(7,'키')

이름  나이     직업     국적    키          재산
4     헐크  33  핵물리학자     미국  270  1000000000
1     토르  45      신  아스가르드  190         NaN
3   원더우먼  27     공주  데미스키라  178         NaN
2  스파이더맨  18   고등학생     미국  177         600
0   아이언맨  58    CEO     미국  174 11500000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [165]:
df[['이름','나이']].nlargest(7,'나이')

이름  나이
0   아이언맨  58
1     토르  45
4     헐크  33
6  블랙위도우  32
3   원더우먼  27
5   캡틴마블  25
2  스파이더맨  18

In [173]:
df.iloc[[1,3,4]]

이름  나이     직업     국적    키         재산
1    토르  45      신  아스가르드  190        NaN
3  원더우먼  27     공주  데미스키라  178        NaN
4    헐크  33  핵물리학자     미국  270 1000000000

In [175]:
df.iloc[1:4]

이름  나이    직업     국적    키  재산
1     토르  45     신  아스가르드  190 NaN
2  스파이더맨  18  고등학생     미국  177 600
3   원더우먼  27    공주  데미스키라  178 NaN

In [176]:
df.iloc[0,0]

'아이언맨'

In [186]:
df.iloc[0:5,3]

0       미국
1    아스가르드
2       미국
3    데미스키라
4       미국
Name: 국적, dtype: object

In [188]:
df2=df.copy()
df2.index = ['a','b','c','d','e','f','g']
df2

이름  나이     직업     국적    키          재산
a   아이언맨  58    CEO     미국  174 11500000000
b     토르  45      신  아스가르드  190         NaN
c  스파이더맨  18   고등학생     미국  177         600
d   원더우먼  27     공주  데미스키라  178         NaN
e     헐크  33  핵물리학자     미국  270  1000000000
f   캡틴마블  25    파일럿     미국  170   340000000
g  블랙위도우  32    스파이    러시아  170    50000000

In [189]:
df2.loc['a']

이름          아이언맨
나이            58
직업           CEO
국적            미국
키            174
재산   11500000000
Name: a, dtype: object

In [190]:
df2.loc['a':'b']

이름  나이   직업     국적    키          재산
a  아이언맨  58  CEO     미국  174 11500000000
b    토르  45    신  아스가르드  190         NaN

In [192]:
df2.loc['a','이름':'직업']

이름    아이언맨
나이      58
직업     CEO
Name: a, dtype: object

In [193]:
df['재산'].isnull()

0    False
1     True
2    False
3     True
4    False
5    False
6    False
Name: 재산, dtype: bool

In [194]:
df[df['재산'].isnull()]

이름  나이  직업     국적    키  재산
1    토르  45   신  아스가르드  190 NaN
3  원더우먼  27  공주  데미스키라  178 NaN

In [195]:
df.isnull().sum()

이름    0
나이    0
직업    0
국적    0
키     0
재산    2
dtype: int64

In [196]:
df['나이'] > 30

0     True
1     True
2    False
3    False
4     True
5    False
6     True
Name: 나이, dtype: bool

In [202]:
df[(df['나이'] > 30) & (df['나이'] < 50)]

이름  나이     직업     국적    키         재산
1     토르  45      신  아스가르드  190        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [207]:
df.loc[(df['나이'] > 30) & (df['나이'] < 50),'이름':'직업']

이름  나이     직업
1     토르  45      신
4     헐크  33  핵물리학자
6  블랙위도우  32    스파이

In [209]:
df.sort_values('키') #오른차순순

이름  나이     직업     국적    키          재산
6  블랙위도우  32    스파이    러시아  170    50000000
5   캡틴마블  25    파일럿     미국  170   340000000
0   아이언맨  58    CEO     미국  174 11500000000
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
1     토르  45      신  아스가르드  190         NaN
4     헐크  33  핵물리학자     미국  270  1000000000

In [211]:
df.sort_values('키',ascending=False) #내림차순

이름  나이     직업     국적    키          재산
4     헐크  33  핵물리학자     미국  270  1000000000
1     토르  45      신  아스가르드  190         NaN
3   원더우먼  27     공주  데미스키라  178         NaN
2  스파이더맨  18   고등학생     미국  177         600
0   아이언맨  58    CEO     미국  174 11500000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [212]:
df.sort_values('재산',ascending=False)

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000
2  스파이더맨  18   고등학생     미국  177         600
1     토르  45      신  아스가르드  190         NaN
3   원더우먼  27     공주  데미스키라  178         NaN

In [213]:
df2

이름  나이     직업     국적    키          재산
a   아이언맨  58    CEO     미국  174 11500000000
b     토르  45      신  아스가르드  190         NaN
c  스파이더맨  18   고등학생     미국  177         600
d   원더우먼  27     공주  데미스키라  178         NaN
e     헐크  33  핵물리학자     미국  270  1000000000
f   캡틴마블  25    파일럿     미국  170   340000000
g  블랙위도우  32    스파이    러시아  170    50000000

In [215]:
df2['국적'] = '대한민국'
df2

이름  나이     직업    국적    키          재산
a   아이언맨  58    CEO  대한민국  174 11500000000
b     토르  45      신  대한민국  190         NaN
c  스파이더맨  18   고등학생  대한민국  177         600
d   원더우먼  27     공주  대한민국  178         NaN
e     헐크  33  핵물리학자  대한민국  270  1000000000
f   캡틴마블  25    파일럿  대한민국  170   340000000
g  블랙위도우  32    스파이  대한민국  170    50000000

In [217]:
df2['전투력'] = [90,100,454,312,44,78,48]
df2

이름  나이     직업    국적    키          재산  전투력
a   아이언맨  58    CEO  대한민국  174 11500000000   90
b     토르  45      신  대한민국  190         NaN  100
c  스파이더맨  18   고등학생  대한민국  177         600  454
d   원더우먼  27     공주  대한민국  178         NaN  312
e     헐크  33  핵물리학자  대한민국  270  1000000000   44
f   캡틴마블  25    파일럿  대한민국  170   340000000   78
g  블랙위도우  32    스파이  대한민국  170    50000000   48

In [219]:
df2['전투력'] -= 50
df2

이름  나이     직업    국적    키          재산  전투력
a   아이언맨  58    CEO  대한민국  174 11500000000   35
b     토르  45      신  대한민국  190         NaN   45
c  스파이더맨  18   고등학생  대한민국  177         600  399
d   원더우먼  27     공주  대한민국  178         NaN  257
e     헐크  33  핵물리학자  대한민국  270  1000000000  -11
f   캡틴마블  25    파일럿  대한민국  170   340000000   23
g  블랙위도우  32    스파이  대한민국  170    50000000   -7

In [221]:
df2.columns = ['이름','연령','하는일','출신국가','신장','금액','파워']
df2

이름  연령    하는일  출신국가   신장          금액   파워
a   아이언맨  58    CEO  대한민국  174 11500000000   35
b     토르  45      신  대한민국  190         NaN   45
c  스파이더맨  18   고등학생  대한민국  177         600  399
d   원더우먼  27     공주  대한민국  178         NaN  257
e     헐크  33  핵물리학자  대한민국  270  1000000000  -11
f   캡틴마블  25    파일럿  대한민국  170   340000000   23
g  블랙위도우  32    스파이  대한민국  170    50000000   -7

In [223]:
df2.drop(index='a')

이름  연령    하는일  출신국가   신장         금액   파워
b     토르  45      신  대한민국  190        NaN   45
c  스파이더맨  18   고등학생  대한민국  177        600  399
d   원더우먼  27     공주  대한민국  178        NaN  257
e     헐크  33  핵물리학자  대한민국  270 1000000000  -11
f   캡틴마블  25    파일럿  대한민국  170  340000000   23
g  블랙위도우  32    스파이  대한민국  170   50000000   -7

In [224]:
df2

이름  연령    하는일  출신국가   신장          금액   파워
a   아이언맨  58    CEO  대한민국  174 11500000000   35
b     토르  45      신  대한민국  190         NaN   45
c  스파이더맨  18   고등학생  대한민국  177         600  399
d   원더우먼  27     공주  대한민국  178         NaN  257
e     헐크  33  핵물리학자  대한민국  270  1000000000  -11
f   캡틴마블  25    파일럿  대한민국  170   340000000   23
g  블랙위도우  32    스파이  대한민국  170    50000000   -7

In [229]:
df2

이름  연령    하는일  출신국가   신장         금액   파워
b     토르  45      신  대한민국  190        NaN   45
c  스파이더맨  18   고등학생  대한민국  177        600  399
d   원더우먼  27     공주  대한민국  178        NaN  257
e     헐크  33  핵물리학자  대한민국  270 1000000000  -11
f   캡틴마블  25    파일럿  대한민국  170  340000000   23
g  블랙위도우  32    스파이  대한민국  170   50000000   -7

In [230]:
df2.dropna()

이름  연령    하는일  출신국가   신장         금액   파워
c  스파이더맨  18   고등학생  대한민국  177        600  399
e     헐크  33  핵물리학자  대한민국  270 1000000000  -11
f   캡틴마블  25    파일럿  대한민국  170  340000000   23
g  블랙위도우  32    스파이  대한민국  170   50000000   -7

In [231]:
df2.dropna(axis=1)

이름  연령    하는일  출신국가   신장   파워
b     토르  45      신  대한민국  190   45
c  스파이더맨  18   고등학생  대한민국  177  399
d   원더우먼  27     공주  대한민국  178  257
e     헐크  33  핵물리학자  대한민국  270  -11
f   캡틴마블  25    파일럿  대한민국  170   23
g  블랙위도우  32    스파이  대한민국  170   -7

In [232]:
df2.fillna(0)

이름  연령    하는일  출신국가   신장         금액   파워
b     토르  45      신  대한민국  190          0   45
c  스파이더맨  18   고등학생  대한민국  177        600  399
d   원더우먼  27     공주  대한민국  178          0  257
e     헐크  33  핵물리학자  대한민국  270 1000000000  -11
f   캡틴마블  25    파일럿  대한민국  170  340000000   23
g  블랙위도우  32    스파이  대한민국  170   50000000   -7

In [234]:
df2.fillna(method='bfill')

C:\Users\EL0021\AppData\Local\Temp\ipykernel_20120\2667140817.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method='bfill')


이름  연령    하는일  출신국가   신장         금액   파워
b     토르  45      신  대한민국  190        600   45
c  스파이더맨  18   고등학생  대한민국  177        600  399
d   원더우먼  27     공주  대한민국  178 1000000000  257
e     헐크  33  핵물리학자  대한민국  270 1000000000  -11
f   캡틴마블  25    파일럿  대한민국  170  340000000   23
g  블랙위도우  32    스파이  대한민국  170   50000000   -7

In [235]:
df2['금액'].fillna(df2['금액'].mean())

b    347500150
c          600
d    347500150
e   1000000000
f    340000000
g     50000000
Name: 금액, dtype: float64

Note: you may need to restart the kernel to use updated packages.
